version: '2'
services:

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - ./config/s2s-python-envoy.json:/etc/s2s-python-envoy.json
      - ./service/gen/kv.pb:/etc/kv.pb
    expose:
      - "9001"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    volumes:
      - ./config/s2s-grpc-envoy.json:/etc/s2s-grpc-envoy.json
    expose:
      - "9211"
